### ISSUE TITLE
ctwat2ctwasm?

### ISSUE THREAD

**Issue by chiefbiiko** [PLSysSec/ct-wasm#1]
hey all, thanks for your awesome work!!!
how do you compile `.wat` files with secret annotations?

**Comment by djrenren** [comment]
We use the reference interpreter for this. So if you go to: https://github.com/plsyssec/ct-wasm-spec

Check out the `interpreter` directory. Once you successfully `make` you can run `wasm -i my_ctwasm.wat -o my_ctwasm.wasm` and it'll do it for you

**Comment by chiefbiiko** [comment]
cool, awesome tool, thanks!
